### ISSUE TITLE
Capital W

### ISSUE THREAD

**Issue by twerff** [emmajane/Font-Face-Kit-for-Steinem#1]
Great kit, really love this font!
But what is happening with the capital W?
![image](https://cloud.githubusercontent.com/assets/3716615/3214532/14d9aee6-efb1-11e3-976c-54543c5574c1.png)

Keep up the good work!
Ciao

**Comment by emmajane** [comment]
Which of the font files are you having a problem with? And what system are you trying to install it on? I haven't been able to replicate this problem locally.

**Comment by twerff** [comment]
Hi Emma, I am using the steinemb-webfont, so Steinem Bold. I see the same problem with the W in the SteinemBold-demo provided with the kit., but only with Steinem Bold. I use Chrome (version 33.0.1750.154 m). 
But I see now that there is no problem when trying it with Internet Explorer. Weird glitch.. Thanks for the quick reply, but it seems a problem on my PC only.

**Comment by emmajane** [comment]
The webfonts were generated by running the TTF files through http://www.fontsquirrel.com/tools/webfont-generator. You could try running the fonts through the generator again to see if there was a glitch which is now fixed?
